### ISSUE TITLE
Implement dark mode using Tailwind

### ISSUE THREAD

**Issue by CarlosZBent** [CarlosZBent/Directorio_trabajos_tech#7]
https://tailwindcss.com/docs/dark-mode

**Comment by shubhamku044** [comment]
Can I take this issue?

**Comment by CarlosZBent** [comment]
> Can I take this issue?

@shubhamku044 Yes please

**Comment by shubhamku044** [comment]
Okay so assign it to me.

**Comment by shubhamku044** [comment]
Is this the thing you wanted?

![image](https://user-images.githubusercontent.com/77788249/216061260-7e44ef79-6d62-4aed-9a8b-c05ca9ccae29.png)
